[package]
name = "osquery_types"
version = "0.1.0"
authors = ["Insanitybit <insanitybit@gmail.com>"]
edition = "2018"

description = "Common structures for OSQuery tables"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.39"
